---
#single pod with single container attached with host storage
apiVersion: v1
kind: Pod
metadata:
  name: database
  namespace: twitter
  labels:
    app: psql
    tier: backend
    version: master
spec:
  containers:
  - name: psql
    image: postgres
    env:
      - name: POSTGRES_PASSWORD
        value: Password@123
    ports:
      - containerPort: 5432
    volumeMounts:
      - name: pgdata
        mountPath: /var/lib/postgresql/data
  volumes:
  - name: pgdata
    hostPath:
      path: /var/lib/postgres
      type: DirectoryOrCreate


*****************************************************************************************************************
---
#single pod with single container attached with host storage
apiVersion: v1
kind: Pod
metadata:
  name: database
  namespace: twitter
  labels:
    app: httpd
    tier: backend
    version: master
spec:
  containers:
  - name: httpd
    image: httpd
    ports:
      - containerPort: 80
    volumeMounts:
      - name: httpdata
        mountPath: /usr/local/apache2/htdocs/
  volumes:
  - name: httpdata
    hostPath:
      path: /var/lib/httpd/
      type: DirectoryOrCreate
